import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import '@repo/ui/styles.css';
import './globals.css';
import QueryClientProviderWrapper from '@/providers/queryClient-provider';
import { Toaster } from '@repo/ui/sonner';

export const metadata: Metadata = {
  title: 'Workflow',
  description: 'Generated by workflow',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <QueryClientProviderWrapper>
          {children}
          <Toaster />
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
