import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import '@repo/ui/styles.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Workflow',
  description: 'Generated by workflow',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>{children}</body>
    </html>
  );
}
